### ISSUE TITLE
Sandbox enhancements

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/sandbox#14]
_From @djtfmartin on August 19, 2014 10:38_

_migrated from:_ https://code.google.com/p/ala/issues/detail?id=145
_date:_ Thu Aug  8 16:42:48 2013
_author:_ moyesyside

---

Original Issue reported by Project Member Reported by moyesyside, Sep 28, 2011 - [https://code.google.com/p/ala-portal/issues/detail?id=149](https://code.google.com/p/ala-portal/issues/detail?id=149)

Project Member Reported by moyesyside@gmail.com, Sep 28, 2011 
1) Mandatory authentication for data upload
2) Non-sequential IDs for data resources
3) Block view all - unless the user has ALA privileges
4) Dynamic facets

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#32_

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 10:38_


*date:* Thu Aug  8 22:31:46 2013
*author:* moyesyside
 ---

*(No comment was entered for this change.)*

 ---
**UPDATES:**
*Labels:* Sandbox

**Comment by M-Nicholls** [comment]
these are done:
    Mandatory authentication for data upload
     Dynamic facets

are these still required?

Non-sequential IDs for data resources - why is this a requirement?
Block view all - unless the user has ALA privileges

**Comment by M-Nicholls** [comment]
covered in other issues
