### ISSUE TITLE
Data set description page

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/sandbox#28]
simplified, single page for a user to edit a data description:
backended wit hthe collectory:

Data Resource Details
(s) DatasetID:drt# or dr#
(s) Draft (drt#)| Production (dr#) dataset
(u) *_Dataset Name:
(s) Date created
(s) Last updated
(s) Status:
(s) Owner:
(u) (make contact email public Y/N)
(u) *_Description:
(u) Data Generalisations
(u) Information Withheld
(u) *_License:
(u) *_Citation:
(s) Source File:
(s) Sandbox link:

Actions:
Cancel
Edit
Save
Submit
Delete
View current data – (to upload staging with drt# or biocache with dr#)
Load/update data – (to sandbox preview with drt#)
Load to Production (Admin only, if is a drt# then convert to dr#
locks dr# until loaded then set to “data available”)

(s) – system provides the value, not user editable
(u) – user editable
- \*  minimum user fields to submit a data set

**Comment by M-Nicholls** [comment]
can only be edited by the drt# or dr# owner or ALA Admin

**Comment by M-Nicholls** [comment]
license options:
CC-BY, CC-BY-NC, CC-0 3.0 Australia or 4.0 International only

info and links here: http://creativecommons.org.au/learn/licences/

**Comment by M-Nicholls** [comment]
Status options:
Draft - being created/edited for submission
Submitted - submitted for loading - editing/updating data is locked
Data available - data loaded to production

**Comment by M-Nicholls** [comment]
decline button needs a comment box to say why teh data set was declined
from jenkins console needs a "back" button to data set description

check infomation propagates to collectory description text was missing during a test

modification made in collectory admin need to propagate back to data set description

**Comment by M-Nicholls** [comment]
o	Admin features shouldn’t be visible to non-admin (not just inactive)
o	Error occurred when submitting
o	Can edit others descriptions if not admin if you can get to the page

**Comment by M-Nicholls** [comment]
add option to include your user ID with the records (happens automatically at the moment but needs to be optional and opt in)
Admin only option to add another user ID

**Comment by sadeghim** [comment]
transferred to #53 . closing this one!
