### ISSUE TITLE
Integrate with sandbox

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/sandbox#3]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=64
*date:* Thu Aug  8 05:34:30 2013
*author:* moyesyside
 ---

Original Issue  - [https://code.google.com/p/alageospatialportal/issues/detail?id=736](https://code.google.com/p/alageospatialportal/issues/detail?id=736)

Project Member Reported by adam_col...@tpg.com.au, Oct 19, 2011 
Allow 2 way use with sandbox.ala.org.au
 Oct 19, 2011 Project Member `#1` leebel...@gmail.com 
Adding Dave: We would really like to be able to use the Sandbox for the CSV uploads. Currently forget it. A good test set is "Demo_Random_100x9v.csv" at [http://spatial.ala.org.au/files](http://spatial.ala.org.au/files). 
 Cc: moyesyside Oct 20, 2011 Project Member `#2` moyesyside 
Cheers Lee.

We need to integrate the biocache-store code with the new layers-index, so that this is the API  instead of the old gazetteer which is what we are currently using)  Need to catch up with Adam/Ajay/Gav about the possiblities here to make the point lookups as fast as possible.

We also need to add in support for dynamic fields - done using SOLR's dynamic index fields.

 Cc: natasha....@csiro.au Mar 15, 2012 Project Member `#3` leebel...@gmail.com 
Current thoughts on the utility of this, given time left? 

My 5c - given other priorities, set to LOW
 Cc: -waterand...@gmail.com Labels: -Priority-Medium Priority-Low Mar 15, 2012 Project Member `#4` moyesyside 
I think the one thing the sandbox is missing is the ability to handle and facet on arbitrary data fields including continuous variables. This is all possible but I agree with setting it as a low priority at this stage.

The benefit to the SP would be the ability to handle a richer data upload that included all the DwC terms that we handle/parse/process/cleanup.

 Cc: -gavin.ja...@gmail.com Jul 10, 2013 Project Member `#5` leebel...@gmail.com 
Re-assign to Dave but still Low priority. The SP Facet on CSV import fields is still a deal breaker? In the SP, ANY point data can be imported (not just biological records) as with the wind farm case study and faceted on any import field (other than id, lat, long).
 Owner: moyesyside Cc: -ajay.ranipeta -moyesyside -natasha....@csiro.au chris.fl...@gmail.com Jul 10, 2013 Project Member `#6` moyesyside 
thanks Lee. Integration is done from sandbox to SP, it just requires the user to start at [http://sandbox.ala.org.au](http://sandbox.ala.org.au).
Support is in the sandbox for faceting on any field.

e.g. [http://sandbox.ala.org.au/hubs-webapp/occurrences/search?q=data_resource_uid:drt1407](http://sandbox.ala.org.au/hubs-webapp/occurrences/search?q=data_resource_uid:drt1407)

see [http://www.ala.org.au/blogs-news/data/upload-your-data/](http://www.ala.org.au/blogs-news/data/upload-your-data/)

So we just need the UI integration on the SP
 Jul 10, 2013 Project Member `#7` leebel...@gmail.com 
OK, given this, I reckon it's worth a another integration step? Locations of change are

1. Add to map | Species | Import points
2. Tools | Points to grid | Import points
3. Tools | Scatterplot | Import points
4. Tools | Scatterplot list | Import points
5. Tools | GDM | Import points
6. Import | Import points
6. Tools predict | Import points

(Basically the same as the required alignment of Species List in 1064. It may therefore be expedient to do both at the same time.

 Labels: -Priority-Low Priority-High

**Comment by adam-collins** [comment]
sandbox in use by SP
