### ISSUE TITLE
Sandbox Data screen

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/sandbox#30]
Sandbox uploaded data screen
current screen layout - 
Tabs - Data table, map etc
Facets

Actions
View/edit metadata (if drt# exists)
Submit data (opens data set description page with existing data resource name and drt#)
Reload data

**Comment by M-Nicholls** [comment]
security to prevent viewing all data sets should be in place (e.g. http://ala-dury.it.csiro.au/ala-hub/occurrences/search?q=data_resource_uid:* still works)

navigation controls needed:
re-load data (to preview screen)
to data set list
data set description

In record details ALA user Id is automatically added to the records - may not be true, need to a control as part of the load from preview to data data screen to optionally add it to the records

**Comment by M-Nicholls** [comment]
o	Dots don’t show on map (map on record details works)

**Comment by sadeghim** [comment]
Still can see the all temporary records for all users: http://sandbox.ala.org.au/ala-hub/occurrences/search?q=data_resource_uid:*
