### ISSUE TITLE
ala-charts-plugin to use new biocache-service /chart

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/sandbox#40]
This should go on a new ala-charts-plugin branch. 

The new biocache-service /chart ws
https://github.com/AtlasOfLivingAustralia/biocache-service/blob/chart/src/main/java/au/org/ala/biocache/web/ChartController.java#L97

One usage in ala-charts-plugin that requires change, wsCallAndRender
https://github.com/AtlasOfLivingAustralia/ala-charts-plugin/blob/master/web-app/js/ALAChart.js#L272

Also consider the additional chart configuration options that will align with the /chart ws.

**Comment by javier-molina** [comment]
Chart paramenters to support are defined in #39 

This tickets implements only point 3. 

1. was already implemented, 2. was implemented as part of #42  and 4. is just the use of 2 and 3 at the same time.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/ala-charts-plugin/review/ACP-CR-2
