### ISSUE TITLE
Download the processed version of your data fails

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/sandbox#6]
After validating the data and uploading it, press 'download the processed version of your data' produces the error

"A reasonTypeId must be provided"
![capture](https://cloud.githubusercontent.com/assets/6656350/4212895/f8fe2a08-38a8-11e4-80c7-223bd041daba.jpg)
![capture_2](https://cloud.githubusercontent.com/assets/6656350/4212897/fd38f864-38a8-11e4-9344-8e70beaa118c.jpg)

**Comment by nickdos** [comment]
Just tested this and download worked for me - must've been fixed so closing
